[project]
name = "dbt-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.34",
    "langgraph>=0.2.33",
    "python-dotenv>=1.0",
]
